# 2024년 8월 21일 연습

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = [1,2,3]

arr = np.array(data)

arr

array([1, 2, 3])

##### np.array(data) -> array로 변환

##### 넘파이 모듈의 array 함수에 파이썬 리스트를 넘겨주면 ndarray 타입의 객체를 반환

In [4]:
print(arr)

[1 2 3]


In [5]:
type(arr)

numpy.ndarray

##### numpy를 사용하면 우리가 엑셀에서 하던 것과 같은 연산을 파이썬으로 쉽게 할 수 있다.

In [6]:
# array를 안 썼을 때는 for 문을 써야함

result = []
for i in data:
    result.append(i*10)

print(result)

[10, 20, 30]


In [8]:
data = [1,2,3]
arr = np.array(data)

result = arr*10

result # 반복문을 사용하지 않아 코드도 짧고 실행속도도 더 빠르다

array([10, 20, 30])

In [10]:
data2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(data2d[0])

# row 단위로 값을 가져올 수 있음, 하지만 칼럼은 x

[1, 2, 3]


In [11]:
data2d = [
    
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(data2d)

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr[:,1]

array([2, 5, 8])

In [13]:
data1 = [
    [1,2],
    [3,4],
    [5,6]
]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1.dtype # dtype의 int32는 ndarray에 저장된 각각의 데이터가 32비트로 표현할 수 있는 정수라는 뜻

dtype('int32')

In [16]:
arr1.ndim

2

In [17]:
arr1.shape

(3, 2)

In [18]:
data = [1,2,3,4]
array1 = np.array(data)

array1.shape # 1차원 데이터를 뜻하며, 첫 번째 값이 로우의 길이가 아닌 데이터의 길이

(4,)

In [19]:
data1 = [
    [1],
    [2],
    [3],
    [4]
]

array2 = np.array(data1)

array2.shape  # 4행 1열로 저장된 2차원 데이터의 shape

(4, 1)

##### 넘파이는 특정 값으로 구성된 ndarray 객체를 생성하는 몇가지 함수를 제공

##### zeros, ones 함수

In [20]:
print(np.ones(3))
print(np.zeros(3))

[1. 1. 1.]
[0. 0. 0.]


In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
size =(3,4)

np.zeros(size)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
# 넘파이 arange 함수는 최대 세 개의 파라미터를 입력 할 수 있으며, 지정된 범위의 규칙적인 숫자를 갖는 ndarray 객체를 반환

a = np.arange(5)
print(a)

[0 1 2 3 4]


In [28]:
b = np.arange(1,5)

print(b)

[1 2 3 4]


In [30]:
c = np.arange(1,6,2)
print(c)

[1 3 5]


In [33]:
a = np.arange(1,7)

a.reshape((3,2)) # reshape method는 반드시 원본 데이터를 고려해서 입력해야함


array([[1, 2],
       [3, 4],
       [5, 6]])