In [3]:
import pandas as pd
# !pip install torch torchvision

^C


In [5]:
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

In [6]:
import torch
describe(torch.Tensor(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.8495, 0.6503, 0.8379],
        [0.1379, 0.9753, 0.9343]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-1.1256, -0.7557,  1.5005],
        [ 0.4676, -1.1703,  0.7053]])


In [8]:
import torch
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])
