# 8월 22일 2024년 연습

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3], dtype = np.uint8)

print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [5]:
arr = arr.astype('int8')

In [6]:
arr

array([1, 2, 3], dtype=int8)

In [7]:
print(np.nan, type(np.nan)) # Not A Number
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [8]:
arr = np.array([1,2,3])

print(arr + np.nan)
print(arr+ np.inf)

[nan nan nan]
[inf inf inf]


In [12]:
arr = np.arange(4).reshape((2,2))
arr[0][0]

0

In [13]:
%timeit arr[0,0]

85.8 ns ± 1.29 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [14]:
%timeit arr[0][0]

197 ns ± 1.91 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


##### 하나 이상의 데이터를 가져오는 슬라이싱

In [17]:
arr = np.arange(4)

arr[:2]

array([0, 1])

In [18]:
target = [0,2]

arr[target]

array([0, 2])

# 이차원 데이터의 슬라이싱

In [19]:
arr1 = np.arange(20).reshape((4,5))

arr1[:,3]

array([ 3,  8, 13, 18])

In [21]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
arr1[1:,2:] # 해냈당

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

# 2.5 브로드 캐스팅

In [25]:
a = np.array([1,2,3])
b = np.array([2,3,4])

print(a+b)
print(a*b)
print(a%b)

# 같은 크기를 갖는 두 개의 ndarray간의 연산을 살펴보면

# 같은 인덱스를 갖는 데이터 간의 연산이 적용되고, 계산된 결과가 같은 인덱스의 ndarray에 저장



[3 5 7]
[ 2  6 12]
[1 2 3]


In [26]:
print(a+3)

[4 5 6]


#### 브로드 캐스팅이 적용되기 위한 조건

##### (1) 뒤축(trailing axes) 길이가 같다.
##### (2) 비교하는 어느 한 축의 길이가 1이다.

#### 금융 데이터를 이용해서 브로드 캐스팅을 연습해봅시다.

In [28]:
high = [92700,92400,92100,94300,92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

print(arr_high - arr_low)

[2700 1300  400 2200 1400]


In [36]:
price = np.array([arr_high,
         arr_low])
weight = np.array((3,2)).reshape((2,1))

In [38]:
weight_price =price*weight
diff = weight_price[:1,:]- weight_price[1:,:]

In [39]:
diff

array([[98100, 95000, 92900, 98700, 95100]])

In [41]:
weight_price.reshape((5,2))

array([[278100, 277200],
       [276300, 282900],
       [276900, 180000],
       [182200, 183400],
       [184200, 181800]])

# 2.6 조건연산

In [42]:
arr = np.array([10,20,30])

In [44]:
print(arr>10)

[False  True  True]


In [45]:
cond = arr>10

arr[cond]

array([20, 30])

In [48]:

# 얻어온 조건이 모두 참인지 여부를 확인하고 싶은 경우

print(cond.all())

print(cond.any())

False
True


In [49]:
arr = np.array([10,20,30])
cond0 = arr > 10
cond1 = arr < 30

arr[cond0&cond1]

array([20])

In [50]:
arr = np.array([10,20,30])
arr = np.where(arr>10,1,0)



# np.where, 백테스팅에 잘 쓰일 수도 있겠네

In [55]:
arr1 = np.arange(30).reshape(5,6)
arr1 = np.where(arr1>15, 1, 0)

In [56]:
arr1

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

##### 10보다 크면 10을 더하고, 10보다 작으면 10을 빼기

In [58]:
arr1 = np.arange(30).reshape(5,6)
arr2 = np.where(arr1>10, arr1+10, arr1-10)

arr2

array([[-10,  -9,  -8,  -7,  -6,  -5],
       [ -4,  -3,  -2,  -1,   0,  21],
       [ 22,  23,  24,  25,  26,  27],
       [ 28,  29,  30,  31,  32,  33],
       [ 34,  35,  36,  37,  38,  39]])

#### LG 전자의 일자별 종가가 ndarray로 저장되어 있음
##### 주가가 85000 이하로 떨어진 날은?

In [62]:
lge = np.array([93000, 82400, 99100, 81000, 72300])

lge_drop = np.where(lge<=85000,1,0)

print(lge_drop)
print(lge_drop.sum())

[0 1 0 1 1]
3


# 2.7 함수와 메서드

In [63]:
arr = np.arange(8).reshape((4,2))

arr.sum()

28

In [64]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [67]:
print(arr.sum(axis = 0))
print(arr.sum(axis = 1))

[12 16]
[ 1  5  9 13]


##### numpy를 이용해서 임의의 숫자 만들기

In [76]:
np.random.randint(3) # 0부터 2까지 숫자중 하나를 랜덤으로

0

In [77]:
np.random.randint(46,size = 5)

array([20, 10,  2, 32, 14])

In [78]:
np.random.randint(100, size = (3,2))

array([[ 1, 14],
       [96, 42],
       [23, 19]])

In [80]:
x = np.linspace(0,10,3)

In [81]:
y = x**2

In [82]:
y

array([  0.,  25., 100.])

In [86]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.vstack([a,b])
d = np.hstack([a,b])

print(c)
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [85]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 판다스 시리즈

In [87]:
import pandas as pd

In [88]:
data = np.arange(5)

data_series = pd.Series(data)

data_series

0    0
1    1
2    2
3    3
4    4
dtype: int32

#### Series의 index

In [93]:
import pandas as pd

data =[1000,2000,3000]

data_series = pd.Series(data)

print(data_series.index) # 자료구조 RangeIndex 객체가 들어 있으며, 0부터 2까지 1씩 증가하는 숫자가 들어 있다고 알려줌
print(data_series.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [94]:
# index 변수에 리스트 혹은 ndarray로 데이터를 전달하면 자동으로 맵핑된 RangeIndex가 제거되고 지정한 값으로 대체됩니다. 당연하게도 데이터와 같은 개수의 인덱스를 넣어야 합니다.

In [97]:
data = [3000,4000,5000]
data_series = pd.Series(data)

data_series.index = ['메론', '사과', '수박']

data_series

메론    3000
사과    4000
수박    5000
dtype: int64

In [98]:
data = [3000,4000,5000]
index = ['메론','사과','레몬']

data_series = pd.Series(data, index)

data_series

메론    3000
사과    4000
레몬    5000
dtype: int64

In [99]:
data = [1000,2000,3000]
index = ['메론','수박','사과']

series_data = pd.Series(data = data, index = index)

print(series_data)

메론    1000
수박    2000
사과    3000
dtype: int64


In [100]:
v =[1000,2000,3000]
k = ['메로나', '수박', '레몬']

data_series = pd.Series(data = v, index = k)


In [101]:
data_series

메로나    1000
수박     2000
레몬     3000
dtype: int64

##### reindex method

In [105]:
data_series_2 = data_series.reindex(['메로나','레몬','구구콘'])

data_series_2

# 없는 index는 결측치로 처리

메로나    1000.0
레몬     3000.0
구구콘       NaN
dtype: float64

In [106]:
price = [50000, 50100,50500, 51000,49000]
date = ['2024-05-21','2024-05-22','2024-05-23','2024-05-24','2024-05-25']

stock_series = pd.Series(data = price, index = date)

stock_series

2024-05-21    50000
2024-05-22    50100
2024-05-23    50500
2024-05-24    51000
2024-05-25    49000
dtype: int64

##### 딕셔너리를 사용해서 시리즈를 한 번에 만들 수 있음



In [109]:
data = {

    '2024-06-20':'57000',
    '2024-06-21':'58000',
    '2024-06-22':'59000',
    '2024-06-23':'58000',
    '2024-06-24':'49000'
}

data_series = pd.Series(data)

data_series

2024-06-20    57000
2024-06-21    58000
2024-06-22    59000
2024-06-23    58000
2024-06-24    49000
dtype: object

In [110]:
data_series.index

Index(['2024-06-20', '2024-06-21', '2024-06-22', '2024-06-23', '2024-06-24'], dtype='object')

In [114]:
print(data_series.iloc[0])
print(data_series.loc['2024-06-21'])

57000
58000


In [115]:
data_series.iloc[0]

'57000'

In [116]:
data_series

2024-06-20    57000
2024-06-21    58000
2024-06-22    59000
2024-06-23    58000
2024-06-24    49000
dtype: object

In [117]:
data_series.iloc[:3]

2024-06-20    57000
2024-06-21    58000
2024-06-22    59000
dtype: object

In [118]:
data_series.loc['2024-06-20':'2024-06-22']

2024-06-20    57000
2024-06-21    58000
2024-06-22    59000
dtype: object

# 3.6 시리즈의 수정, 추가, 삭제

In [ ]:
from pandas import Series